name: Bot3
 
on: push

env:
  TZ: America/Recife

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 525600

    steps:
       - name: Checkouts
         uses: actions/checkout@master
         
       - name: Initializing environments
         continue-on-error: true
         timeout-minutes: 100
         run: |
              git config --global user.name "shinchan76"
              git config --global user.email "secrets.EMAILGIT"
              mkdir tmp && cd tmp
              git clone 'https://github.com/Shinchan74/ErfanGSIs' bobot

       - name: Setup Erfan
         continue-on-error: true
         timeout-minutes: 10
         run: |
              git clone --recurse-submodules https://github.com/Shinchan74/ErfanGSIs ErfanGSIs
              cd Erf*; sudo bash setup.sh

       - name: Freeing up memory
         run: |
              sudo apt-get remove -y '^ghc-8.*' '^dotnet-.*' '^llvm-.*' 'php.*' azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel account-plugin-facebook account-plugin-flickr account-plugin-jabber account-plugin-salut account-plugin-twitter account-plugin-windows-live account-plugin-yahoo aisleriot brltty duplicity empathy empathy-common example-content gnome-accessibility-themes gnome-contacts gnome-mahjongg gnome-mines gnome-orca gnome-screensaver gnome-sudoku gnome-video-effects gnomine landscape-common libreoffice-avmedia-backend-gstreamer libreoffice-base-core libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw libreoffice-gnome libreoffice-gtk libreoffice-impress libreoffice-math libreoffice-ogltrans libreoffice-pdfimport libreoffice-style-galaxy libreoffice-style-human libreoffice-writer libsane libsane-common mcp-account-manager-uoa python3-uno rhythmbox rhythmbox-plugins rhythmbox-plugin-zeitgeist sane-utils shotwell shotwell-common telepathy-gabble telepathy-haze telepathy-idle telepathy-indicator telepathy-logger telepathy-mission-control-5 telepathy-salut totem totem-common totem-plugins printer-driver-brlaser printer-driver-foo2zjs printer-driver-foo2zjs-common printer-driver-m2300w printer-driver-ptouch printer-driver-splix; rm -rf /usr/share/dotnet/; sudo rm -rf "/usr/local/share/boost"; sudo rm -rf "$AGENT_TOOLSDIRECTORY"; sudo swapoff -av; sudo rm -rf /mnt/swapfile

       - name: Setup Bot3
         continue-on-error: true
         timeout-minutes: 10
         run: |
              git clone https://${{ secrets.USERNAME }}":${{ secrets.GITTOKEN }}"@github.com/Project-WKF/Bot3-Jar bobot
              mv bobot/*.jar .; rm -rf bobot
              mv *.jar BoboBot.jar

       - name: Run Bot3 in first time
         continue-on-error: true
         timeout-minutes: 3
         run: |
               java -jar BoboBot.jar
         
       - name: Add values
         continue-on-error: true
         timeout-minutes: 1
         run: |
              rm -rf configs/config.prop
              cd configs
              touch config.prop
              echo "bot-token=${{ secrets.TOKEN }}" >> "config.prop"
              echo "bot-username=Wino_Builder" >> "config.prop"
              echo "bot-master=1484394942" >> "config.prop"
              echo "bot-sf-pass=${{ secrets.PASSWORD }}" >> sf-creds.config
              echo "bot-sf-proj=Winogsi" >> sf-creds.config
              echo "bot-sf-user=shinchan" >> sf-creds.config
              echo "bot-announcement-id=-1458060386" >> sf-creds.config
              echo "bot-sf-host=frs.sourceforge.net" >> sf-creds.config
              echo "bot-send-announcement=true" >> sf-creds.config
             
       - name: Run Bot3
         continue-on-error: true
         timeout-minutes: 350
         run: sudo java -jar BoboBot.jar
         
       - name: Loop workflow
         continue-on-error: true
         timeout-minutes: 1
         run: |
              cd tmp/bobot
              date=`date +%Y%m%d%h%m`
              echo "1" >> push.txt
              git add .
              git commit -m "[ $Date ] - loop workflow"
              
       - name: Reruns
         continue-on-error: true
         timeout-minutes: 5
         run: |
              cd tmp/bobot
              sudo apt-get install expect -y
              expect -c "
              spawn git push -f 
              expect \"Username\"
              send \"Wino_Builder\r\"
              expect \"Password\"
              send \"${{ secrets.PASSWORD }}\r\"
              expect \"master -> master\"
              set timeout -10
              interact"
